Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-08, with the labels that each got.

#88 Support static IP address
  oracle/api/v1alpha1/instance_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/samples/v1alpha1_instance_gcp_lb.yaml
  oracle/controllers/resources.go
  oracle/operator.yaml
Labels: approved, cla: yes, lgtm, size/M

#90 Reduce integration test flakiness
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
Labels: approved, cla: yes, lgtm, size/XS, testing

#91 Fixup some scripts
  oracle/build/dbimage/image_build.sh
  oracle/scripts/redeploy.sh
Labels: approved, cla: yes, enhancement, lgtm, size/M

#92 Fix instance_controller_test flakiness
  oracle/controllers/instancecontroller/instance_controller_test.go
Labels: size/XS, lgtm, cla: yes, approved

#93 [Backup Schedule] Move CronAnything from oracle to common.
  BUILD.bazel
  common/api/v1alpha1/BUILD.bazel
  common/api/v1alpha1/cronanything.go
  common/api/v1alpha1/instance.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  common/controllers/BUILD.bazel
  common/controllers/cronanything_controller.go
  common/controllers/cronanything_controller_test.go
  common/controllers/operations.go
  oracle/api/v1alpha1/cronanything_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_cronanythings.yaml
  oracle/config/rbac/role.yaml
  oracle/controllers/backupschedulecontroller/backupschedule_controller.go
  oracle/controllers/backupschedulecontroller/backupschedule_controller_test.go
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/backupschedulecontroller/operations.go
  oracle/controllers/cronanythingcontroller/BUILD.bazel
  oracle/controllers/cronanythingcontroller/cronanything_controller.go
  oracle/controllers/cronanythingcontroller/operations.go
  oracle/main.go
  oracle/operator.yaml
Labels: lgtm, cla: yes, size/XXL, ok-to-test, approved

#96 Move ConfigSpec from oracle to common
  common/api/v1alpha1/BUILD.bazel
  common/api/v1alpha1/config.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  oracle/api/v1alpha1/config_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/operator.yaml
Labels: lgtm, size/L, cla: yes, approved

#95 Bugfix: fix SEGFAULT in instance controller
  oracle/controllers/instancecontroller/utils.go
Labels: size/XS, lgtm, cla: yes, approved

#94 [PE] Force Bazel to run 10 test jobs
  oracle/Makefile
Labels: size/XS, lgtm, cla: yes, approved

#97 Bugfix: restore LRO functionality broken by the recent refactoring change
  oracle/controllers/config_agent_helpers.go
Labels: size/XS, lgtm, cla: yes, approved

#98 godror upgrade to 0.25.3
  WORKSPACE
  go.mod
  go.sum
  hack/0001-Patch-to-add-bazel-support.patch
Labels: lgtm, size/L, cla: yes, approved

#100 Fix instance restore
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/utils.go
Labels: size/M, lgtm, cla: yes, approved

#101 [PE] Increase DB provisioning timeout in phys backup test
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
Labels: size/XS, lgtm, cla: yes, approved

#103 Changing `SectionSize` from int to resource.Quantity
  docs/content/backup-restore/rman-backups.md
  oracle/api/v1alpha1/BUILD.bazel
  oracle/api/v1alpha1/backup_types.go
  oracle/api/v1alpha1/backup_types_test.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/config/samples/v1alpha1_backup_rman3.yaml
  oracle/config/samples/v1alpha1_backup_rman4.yaml
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupschedulecontroller/backupschedule_controller_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/operator.yaml
  oracle/pkg/agents/backup/BUILD.bazel
  oracle/pkg/agents/backup/backup.go
  oracle/pkg/agents/backup/backup_test.go
  oracle/pkg/agents/config_agent/server/BUILD.bazel
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: lgtm, size/L, cla: yes, approved

#104 Reduce Oracle DB image size
  oracle/build/dbimage/Dockerfile
  oracle/build/dbimage/cloudbuild-18c-xe.yaml
  oracle/build/dbimage/image_build.sh
  oracle/build/dbimage/install-oracle-18c-xe.sh
  oracle/build/dbimage/install-oracle.sh
  oracle/build/dbimage/oracle-preinstall.sh
Labels: lgtm, size/L, cla: yes, approved

#105 Make last transition time sensitive to changes in reason field of con…
  oracle/pkg/k8s/condition.go
  oracle/pkg/k8s/condition_test.go
Labels: size/XS, lgtm, cla: yes, approved

#102 [Backup Schedule] make backupschedule a general framework
  common/api/v1alpha1/BUILD.bazel
  common/api/v1alpha1/backup.go
  common/api/v1alpha1/backupschedule.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  common/controllers/BUILD.bazel
  common/controllers/backupschedule_controller.go
  common/controllers/backupschedule_controller_test.go
  common/controllers/cronanything_controller.go
  common/controllers/cronanything_controller_test.go
  go.sum
  oracle/api/v1alpha1/backup_types.go
  oracle/api/v1alpha1/backupschedule_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/controllers/backupschedulecontroller/BUILD.bazel
  oracle/controllers/backupschedulecontroller/backupschedule_controller.go
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/backupschedulecontroller/operations.go
  oracle/controllers/cronanythingcontroller/BUILD.bazel
  oracle/controllers/cronanythingcontroller/operations.go
  oracle/main.go
  oracle/operator.yaml
Labels: lgtm, needs-ok-to-test, cla: yes, size/XXL, approved

#106 Create image type flag file during startup of oracledb container
  oracle/cmd/dbdaemon_proxy/BUILD.bazel
  oracle/cmd/dbdaemon_proxy/dbdaemon_proxy.go
  oracle/pkg/agents/consts/consts.go
Labels: size/M, lgtm, cla: yes, approved

#108 Improve detection of seeded/unseeded images
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_proxy.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.proto
  oracle/pkg/agents/oracle/dbdaemon_proxy_grpc.pb.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
Labels: lgtm, cla: yes, size/XXL, approved

#110 Enhance detection of CDB
  oracle/pkg/database/provision/common.go
Labels: size/XS, lgtm, cla: yes, approved

#109 Detect rejected parameter updates and initiate rollback. b/190833793
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
Labels: size/M, lgtm, cla: yes, approved

#112 Update to use github kubebuilder download.
  oracle/scripts/install_prow_deps.sh
Labels: size/XS, lgtm, cla: yes, approved

#111 Add docs for Oracle 19c and OCR images
  README.md
  docs/content/quickstart-12c-ee.md
  docs/content/quickstart-18c-xe.md
  docs/content/quickstart-19c-ee.md
  docs/content/quickstart.md
Labels: lgtm, cla: yes, size/XXL, approved

#116 Changed config util methods to get the default disk information from …
  common/pkg/utils/utils.go
  common/pkg/utils/utils_test.go
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/common.go
  oracle/controllers/resources.go
Labels: lgtm, size/L, cla: yes, approved

#115 Modify express installation script to also support Oracle 19c
  oracle/build/dbimage/install-oracle.sh
  oracle/config/samples/v1alpha1_instance_19c_EE.yaml
  oracle/config/samples/v1alpha1_instance_19c_EE_express.yaml
  oracle/scripts/deploy/install.sh
Labels: lgtm, size/L, cla: yes, approved

#114 Remove dependence on .metadata file
  oracle/cmd/init_oracle/stop_oracle.sh
  oracle/pkg/database/provision/common.go
Labels: size/M, lgtm, cla: yes, approved

#117 [PE] Fix race condition in instance controller functional test
  oracle/Makefile
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
Labels: size/S, lgtm, cla: yes, approved

#118 Retry if LRO is not done
  oracle/controllers/instancecontroller/instance_controller_restore.go
Labels: size/S, lgtm, cla: yes, approved

#120 [PE] Increase datapump test timeout 2m->5m
  oracle/controllers/inttest/datapumptest/datapump_test.go
Labels: size/XS, lgtm, cla: yes, approved

#121 Add accessModes and selector in DiskSpec
  common/api/v1alpha1/disk.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/operator.yaml
Labels: lgtm, size/L, cla: yes, ok-to-test, approved

#119 [PE] Run slow unseeded tests only in canary job
  oracle/Makefile
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: size/M, lgtm, cla: yes, approved

#122 Modify the Config controller to support multiple instances
  oracle/controllers/configcontroller/config_controller.go
  oracle/controllers/configcontroller/config_controller_test.go
Labels: lgtm, size/L, cla: yes, approved

#123 Test creation of two instances within one namespace
  oracle/controllers/inttest/instancetest/instance_test.go
Labels: lgtm, size/L, cla: yes, approved
