Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-11, with the labels that each got.

#165 Fix dbdaemon connection from controller
  oracle/controllers/backupcontroller/oracle_backup.go
  oracle/controllers/common.go
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/testhelpers/grpcmocks.go
Labels: size/M, lgtm, cla: yes, approved

#166 Add dev-container make rule
  oracle/Makefile
  oracle/scripts/install_prow_deps.sh
Labels: size/M, lgtm, cla: yes, approved

#173 Adding required APIs for enabling dNFS
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.proto
  oracle/pkg/agents/oracle/dbdaemon_proxy_grpc.pb.go
  oracle/pkg/agents/oracle/oracle.pb.go
  oracle/pkg/agents/oracle/oracle.proto
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
Labels: lgtm, size/L, cla: yes, approved

#170 ConfigAgent: move `DeleteOperation(`
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupcontroller/oracle_backup.go
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/exportcontroller/export_controller_test.go
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/importcontroller/import_controller_test.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/BUILD.bazel
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/BUILD.bazel
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: lgtm, cla: yes, size/XXL, approved

#174 Controller changes to enable dNFS
  oracle/api/v1alpha1/instance_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/operator.yaml
Labels: size/M, lgtm, cla: yes, approved

#172 ConfigAgent: move `BounceDatabase(`
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: size/XL, cla: yes
