Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-12, with the labels that each got.

#167 ConfigAgent: move `RecoverConfigFile(`
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: lgtm, size/L, cla: yes, approved

#171 ConfigAgent: move `SetParameter(`
  oracle/controllers/BUILD.bazel
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: size/XL, cla: yes

#178 [PE] Remove Oracle 12 tests until Oracle releases patches
  oracle/controllers/inttest/datapumptest/datapump_test.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/inttest/snapbackuptest/snapshot_backup_test.go
  oracle/controllers/inttest/usertest/user_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: size/M, lgtm, approved

#179 [PE] Make functional test helpers more generic
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupschedulecontroller/functest/BUILD.bazel
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/configcontroller/BUILD.bazel
  oracle/controllers/configcontroller/config_controller_test.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/exportcontroller/BUILD.bazel
  oracle/controllers/exportcontroller/export_controller_test.go
  oracle/controllers/importcontroller/BUILD.bazel
  oracle/controllers/importcontroller/import_controller_test.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/instance_lock_test/BUILD.bazel
  oracle/controllers/instancecontroller/instance_lock_test/instance_lock_test.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/envtest.go
  oracle/controllers/validationstest/BUILD.bazel
  oracle/controllers/validationstest/crd_validation_test.go
Labels: lgtm, size/L, approved
