Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-05, with the labels that each got.

#7 Update makefile prepare-release rule
  oracle/Makefile
Labels: testing

#11 Fix deepcopy format
  oracle/api/v1alpha1/zz_generated.deepcopy.go
Labels: testing

#16 Add InstanceStatus.Phase.
  common/api/v1alpha1/instance.go
  common/api/v1alpha1/phase.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/operator.yaml
Labels: lgtm, size/M

#19 Fix data races in FakeConfigAgentClient.
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/exportcontroller/export_controller_test.go
  oracle/controllers/importcontroller/import_controller_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/grpcmocks.go
Labels: size/L

#20 Fix backup test flakiness.
  oracle/controllers/backupcontroller/backup_controller_test.go
Labels: lgtm, size/S

#22 Add make target to create release dir file tree.
  oracle/Makefile
  oracle/scripts/get_all_logs.sh
Labels: lgtm, size/S

#23 logging the skipping-update info only for an existing DB
  oracle/controllers/instancecontroller/instance_controller.go
Labels: lgtm, needs-ok-to-test, size/XS

#24 [PE] Add a functional test for restore from RestoreFailed state
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: cla: yes, lgtm, size/L

#25 Update go dependencies for Oracle to newer versions
  WORKSPACE
  deps.bzl
  go.mod
  go.sum
  oracle/Makefile
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_cronanythings.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_databases.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_exports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_imports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_releases.yaml
  oracle/controllers/BUILD.bazel
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupschedulecontroller/BUILD.bazel
  oracle/controllers/backupschedulecontroller/backupschedule_controller.go
  oracle/controllers/backupschedulecontroller/backupschedule_controller_test.go
  oracle/controllers/backupschedulecontroller/functest/BUILD.bazel
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/configcontroller/BUILD.bazel
  oracle/controllers/configcontroller/config_controller.go
  oracle/controllers/configcontroller/config_controller_test.go
  oracle/controllers/cronanythingcontroller/BUILD.bazel
  oracle/controllers/cronanythingcontroller/cronanything_controller.go
  oracle/controllers/cronanythingcontroller/cronanything_controller_test.go
  oracle/controllers/cronanythingcontroller/operations.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/exportcontroller/BUILD.bazel
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/importcontroller/BUILD.bazel
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/BUILD.bazel
  oracle/controllers/inttest/datapumptest/BUILD.bazel
  oracle/controllers/inttest/instancetest/BUILD.bazel
  oracle/controllers/inttest/parameterupdatetest/BUILD.bazel
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/controllers/inttest/physbackuptest/BUILD.bazel
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/inttest/releasetest/BUILD.bazel
  oracle/controllers/inttest/snapbackuptest/BUILD.bazel
  oracle/controllers/inttest/snapbackuptest/snapshot_backup_test.go
  oracle/controllers/inttest/usertest/BUILD.bazel
  oracle/controllers/inttest/usertest/user_test.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/envtest.go
  oracle/controllers/validationstest/BUILD.bazel
  oracle/main.go
  oracle/operator.yaml
Labels: cla: yes, lgtm, refactoring, size/XXL

#27 Fix the controller runtime issue caused by merge conflict.
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: cla: yes, lgtm, size/S

#28 [PE] Move all instance restore routines to a separate file.
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
Labels: cla: yes, lgtm, size/XL

#29 Update controller tools to version v0.5.0
  deps.bzl
  go.mod
  go.sum
  oracle/Makefile
  oracle/api/v1alpha1/cronanything_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_cronanythings.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_databases.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_exports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_imports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_releases.yaml
  oracle/operator.yaml
Labels: cla: yes, enhancement, lgtm, size/XXL

#30 [PE] Refactor STS and PVC removal before snapshot restore
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller_restore.go
Labels: cla: yes, lgtm, size/L

#33 Add permissions for leases.coordination.k8s.io
  oracle/config/rbac/role.yaml
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/operator.yaml
Labels: cla: no, lgtm, needs-ok-to-test, size/S
