Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-06, with the labels that each got.

#35 [PE] Increase instance creation timeout in tests
  oracle/controllers/testhelpers/envtest.go
Labels: cla: yes, lgtm, size/XS

#37 Support Kind platform
  oracle/api/v1alpha1/config_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/samples/v1alpha1_config_kind.yaml
  oracle/controllers/common.go
  oracle/controllers/configcontroller/config_controller.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/resources.go
  oracle/operator.yaml
Labels: cla: yes, lgtm, size/M

#36 [OSS] Refactor restore logic into a state machine
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/pkg/k8s/condition.go
Labels: cla: yes, lgtm, size/L

#38 Add reader.Close()
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#41 Update v1alpha1_database_pdb1_gsm.yaml
  oracle/config/samples/v1alpha1_database_pdb1_gsm.yaml
Labels: cla: yes, lgtm, size/XS

#43 Add scripts to manually test dataplane server APIs
  oracle/BUILD.bazel
  oracle/scripts/manual_test/BUILD.bazel
  oracle/scripts/manual_test/test.go
  oracle/scripts/manual_test/test_config_agent.go
  oracle/scripts/manual_test/test_dbdaemon.go
Labels: cla: yes, lgtm, size/L, testing

#45 Remove type attribute in disk spec
  common/api/v1alpha1/disk.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/samples/v1alpha1_config_gcp2.yaml
  oracle/config/samples/v1alpha1_instance.yaml
  oracle/config/samples/v1alpha1_instance_18c_XE.yaml
  oracle/config/samples/v1alpha1_instance_custom_seeded.yaml
  oracle/config/samples/v1alpha1_instance_gcp_ilb.yaml
  oracle/config/samples/v1alpha1_instance_minikube.yaml
  oracle/config/samples/v1alpha1_instance_unseeded.yaml
  oracle/config/samples/v1alpha1_instance_with_backup_disk.yaml
  oracle/operator.yaml
Labels: cla: yes, lgtm, size/M

#46 Add docs for kind platform
  README.md
  docs/content/kind.md
  docs/content/minikube.md
  oracle/config/samples/v1alpha1_config_kind.yaml
  oracle/config/samples/v1alpha1_instance_local.yaml
Labels: cla: yes, documentation, lgtm, size/L

#42 Create guide for pull requests
  docs/contributors/pull-requests.md
Labels: cla: yes, lgtm, size/M

#44 [PE] Integration tests: do not use logf.Logr
  oracle/controllers/inttest/parameterupdatetest/BUILD.bazel
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/inttest/snapbackuptest/snapshot_backup_test.go
  oracle/controllers/inttest/usertest/BUILD.bazel
  oracle/controllers/inttest/usertest/user_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: cla: yes, lgtm, size/M

#48 Add OWNERS file.
  OWNERS
Labels: cla: yes, do-not-merge/invalid-owners-file, lgtm, size/S

#47 Refactor the backup controller.
  oracle/controllers/backupcontroller/backup_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, refactoring, size/M

#50 [PE] Fix RMAN control file snapshot location
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/pkg/agents/backup/backup.go
Labels: approved, cla: yes, lgtm, size/S

#51 Support setting CPU/memory limits for DB pod from API
  common/api/v1alpha1/instance.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  docs/content/backup-restore/restore-from-backups.md
  docs/content/custom-resources/instance.md
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/samples/v1alpha1_instance.yaml
  oracle/config/samples/v1alpha1_instance_18c_XE.yaml
  oracle/config/samples/v1alpha1_instance_gcp_ilb.yaml
  oracle/config/workflows/v1alpha1_instance.yaml
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/physbackuptest/BUILD.bazel
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/resources.go
  oracle/controllers/testhelpers/envtest.go
  oracle/operator.yaml
Labels: approved, cla: yes, enhancement, lgtm, size/L

#49 [PE] Store Oracle /trace/ directory upon test failure
  oracle/Makefile
  oracle/controllers/inttest/datapumptest/datapump_test.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/inttest/snapbackuptest/snapshot_backup_test.go
  oracle/controllers/inttest/usertest/user_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: approved, cla: yes, lgtm, size/M, testing

#52 Use backup reference for restore
  elcarro-oracle-operator.iml
  oracle/api/v1alpha1/instance_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/operator.yaml
Labels: approved, cla: yes, lgtm, size/L

#54 Add backup mode VerifyExists
  oracle/api/v1alpha1/backup_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/operator.yaml
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/k8s/condition.go
Labels: approved, cla: yes, lgtm, size/XXL

#53 Refactor snapshot in backup controller.
  common/pkg/utils/BUILD.bazel
  common/pkg/utils/utils.go
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/resources.go
Labels: approved, cla: yes, lgtm, size/L

#55 Support restore to a new unseeded instance
  oracle/cmd/init_oracle/init_oracle.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/pkg/agents/backup/restore.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy_test.go
  oracle/pkg/database/provision/bootstrap_database_task.go
  oracle/pkg/database/provision/bootstrap_database_task_test.go
  oracle/pkg/database/provision/common.go
  oracle/pkg/k8s/condition.go
Labels: approved, cla: yes, enhancement, lgtm

#56 Improve restore state machine preflight
  oracle/controllers/instancecontroller/instance_controller_restore.go
Labels: approved, cla: yes, enhancement, lgtm, size/XS

#57 Bare metal automation script
  oracle/scripts/deploy/bare-metal-setup.sh
Labels: approved, cla: yes, lgtm, size/L

#58 Remove elcarro-oracle-operator.iml added by mistake
  elcarro-oracle-operator.iml
Labels: approved, cla: yes, size/XS
