Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-07, with the labels that each got.

#59 Add a script to configure service accounts
  hack/configure-service-account.sh
Labels: approved, cla: yes, lgtm, size/L

#61 external restore: backup duration support
  oracle/api/v1alpha1/backup_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/operator.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#62 [PE] Minor fix in controllers.exec() error reporting
  oracle/controllers/exec.go
Labels: approved, cla: yes, lgtm, size/XS

#63 Refactor backup controller
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/resources.go
  oracle/pkg/k8s/condition.go
Labels: approved, cla: yes, lgtm, size/XL

#64 Add ORACLE related env variables to DB image
  oracle/build/dbimage/Dockerfile
  oracle/build/dbimage/cloudbuild-18c-xe.yaml
  oracle/build/dbimage/cloudbuild.yaml
  oracle/build/dbimage/image_build.sh
Labels: approved, cla: yes, lgtm, size/S

#66 Enable Unified Auditing during bootstrapping
  oracle/build/BUILD.bazel
  oracle/build/dbinit/Dockerfile
  oracle/cmd/dbdaemon/BUILD.bazel
  oracle/cmd/dbdaemon/init_dbdaemon.sh
  oracle/cmd/init_oracle/init_oracle.sh
  oracle/controllers/resources.go
Labels: approved, cla: yes, lgtm, size/M

#65 added instance creation integration tests for unseeded images
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/.bazelrc.tmpl
  oracle/controllers/inttest/instancetest/BUILD.bazel
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
  oracle/scripts/integration_test_cluster/create_integration_test_cluster.sh
Labels: approved, cla: yes, lgtm, size/M

#67 Revert "added instance creation integration tests for unseeded images"
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/.bazelrc.tmpl
  oracle/controllers/inttest/instancetest/BUILD.bazel
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
  oracle/scripts/integration_test_cluster/create_integration_test_cluster.sh
Labels: approved, cla: yes, lgtm, size/M

#68 added instance creation integration tests for unseeded images (12c and 19c)
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/.bazelrc.tmpl
  oracle/controllers/inttest/instancetest/BUILD.bazel
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
  oracle/scripts/integration_test_cluster/create_integration_test_cluster.sh
Labels: approved, cla: yes, lgtm, size/M

#69 Fix flaky backup controller test
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/grpcmocks.go
Labels: approved, cla: yes, lgtm, size/L, testing

#70 Use Oracle env vars from DB image for all DB related operations
  oracle/BUILD.bazel
  oracle/cmd/init_oracle/init_oracle.go
  oracle/controllers/BUILD.bazel
  oracle/controllers/resources.go
  oracle/pkg/agents/consts/consts.go
  oracle/pkg/database/common/BUILD.bazel
  oracle/pkg/database/common/common.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemonproxy/BUILD.bazel
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
  oracle/pkg/database/provision/BUILD.bazel
  oracle/pkg/database/provision/bootstrap_database_task.go
  oracle/pkg/database/provision/cdb.go
  oracle/pkg/database/provision/common.go
  oracle/pkg/database/provision/common_test.go
Labels: approved, cla: yes, lgtm, size/L

#71 Support external restore on seeded instance
  oracle/build/dbinit/Dockerfile
  oracle/cmd/init_oracle/BUILD.bazel
  oracle/cmd/init_oracle/init_container.sh
  oracle/cmd/init_oracle/init_oracle.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/resources.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.proto
  oracle/pkg/agents/oracle/dbdaemon_proxy_grpc.pb.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
Labels: approved, cla: yes, enhancement, lgtm

#72 Improve test env cleanup
  oracle/controllers/testhelpers/envtest.go
  oracle/scripts/integration_test_cluster/delete_integration_test_cluster.sh
Labels: approved, cla: yes, lgtm, size/XS

#73 Add integration test for unseeded 19c image from OCR
  oracle/controllers/inttest/.bazelrc.tmpl
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: approved, cla: yes, lgtm, size/S

#74 Cleanup stale forwarding rules and target pools
  oracle/Makefile
  oracle/scripts/integration_test_cluster/cleanup_integration_test_clusters.sh
Labels: approved, cla: yes, lgtm, size/S

#76 Instance controller refactoring.
  oracle/controllers/instancecontroller/instance_controller.go
Labels: approved, cla: yes, lgtm, size/L

#75 Fix uid:pid in loggingsidecar image
  oracle/build/BUILD.bazel
Labels: approved, cla: yes, lgtm, size/XS

#77 Minor fix to check createServices error to avoid panic
  oracle/controllers/instancecontroller/instance_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#79 Minor fix to createServices
  oracle/controllers/instancecontroller/instance_controller.go
Labels: approved, bug, cla: yes, lgtm

#82 Fix flaky instance test with unseeded OCR image
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/instancetest/instance_test.go
Labels: approved, cla: yes, lgtm, size/S

#83 Increase node count for instance integration test
  oracle/controllers/inttest/instancetest/BUILD.bazel
  oracle/scripts/integration_test_cluster/create_integration_test_cluster.sh
Labels: approved, cla: yes, lgtm, size/XS

#80 Moving utility functions to a separate file
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
Labels: approved, cla: yes, lgtm, size/XXL

#81 [PE] Cleanup stale objects in integration test project:
  oracle/scripts/install_prow_deps.sh
  oracle/scripts/integration_test_cluster/cleanup_integration_test_clusters.sh
  oracle/scripts/integration_test_cluster/create_service_account.sh
  oracle/scripts/integration_test_cluster/delete_service_account.sh
Labels: approved, cla: yes, lgtm, size/M

#84 Fix invalid spec in v1alpha1_cronanything.yaml
  oracle/config/samples/v1alpha1_cronanything.yaml
Labels: approved, cla: yes, lgtm, size/XS

#85 Reduce storage usage of integration tests
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: approved, cla: yes, lgtm, size/S, testing

#86 Increase bazel job count to match cluster node count
  oracle/Makefile
Labels: approved, cla: yes, lgtm, size/XS, testing

#87 Use LRO for createCDB/bootstrapCDB
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_parameters_test.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/resources.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/k8s/condition.go
Labels: approved, cla: yes, lgtm, size/XXL
