Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-09, with the labels that each got.

#124 Create adump and cdump dirs for unseeded instance during bootstraping.
  oracle/pkg/database/provision/bootstrap_database_task.go
Labels: size/S, lgtm, cla: yes, approved

#128 Update version number
  oracle/version.go
Labels: size/XS, lgtm, cla: yes, approved

#129 Fix adump path in restore
  oracle/pkg/agents/backup/restore.go
Labels: size/XS, lgtm, cla: yes, approved

#99 Instructions and config to run in AWS EKS
  docs/content/aws.md
  oracle/build/dbimage/aws/buildspec.yml
  oracle/build/dbimage/aws/create-service-role.json
  oracle/build/dbimage/aws/elcarro-ECR-template.json
  oracle/build/dbimage/aws/put-role-policy.json
Labels: size/XL, lgtm, cla: yes, ok-to-test, approved

#127 Add angelawan-jiawan in OWNERS
  OWNERS
Labels: size/XS, lgtm, cla: yes, approved

#126 Add VolumeName in DiskSpec
  common/api/v1alpha1/disk.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/operator.yaml
Labels: size/S, lgtm, cla: yes, ok-to-test, approved

#130 [PE] Improve testenv Update functionality, refactor instance test code
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: lgtm, size/L, cla: yes, approved

#131 [PE] Make K8sDeleteWithRetry wait for object deletion.
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/instancecontroller/instance_controller_parameters_test.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/controllers/inttest/physbackuptest/physical_backup_test.go
  oracle/controllers/inttest/snapbackuptest/snapshot_backup_test.go
  oracle/controllers/inttest/usertest/user_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: lgtm, size/L, cla: yes, approved

#132 [PE] backup_controller_test: properly wait for snapshot backup creation
  oracle/controllers/backupcontroller/backup_controller_test.go
Labels: size/XS, lgtm, cla: yes, approved

#133 Fix volume snapshot filtering issue in the backup controller
  common/pkg/utils/utils.go
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/resources.go
Labels: size/S, lgtm, cla: yes, approved

#135 backup controller unit test
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupcontroller/backup_controller_unit_test.go
  oracle/controllers/backupcontroller/operations.go
  oracle/controllers/backupcontroller/operations_test.go
  oracle/controllers/backupcontroller/oracle_backup.go
  oracle/controllers/backupcontroller/oracle_backup_test.go
  oracle/controllers/instancecontroller/instance_controller_parameters_test.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/main.go
Labels: lgtm, cla: yes, size/XXL, approved

#136 Preserve analysis cache during make test
  oracle/Makefile
Labels: size/XS, lgtm, cla: yes, approved

#134 [PE] DataPump test timeout increase 2m->5m
  oracle/controllers/inttest/datapumptest/datapump_test.go
Labels: size/XS, lgtm, cla: yes, approved

#137 Change 22621 Add a NamespaceMapper.
  common/pkg/ns/BUILD.bazel
  common/pkg/ns/ns.go
  common/pkg/ns/ns_test.go
Labels: lgtm, size/L, cla: yes, approved

#140 Update image build patch version help text and test build to be explicit
  oracle/build/dbimage/image_build.sh
  oracle/scripts/canary_build_dbimage_image_build.sh
Labels: size/XS, lgtm, cla: yes, approved

#138 Create an Instance Lock mechanism
  oracle/api/v1alpha1/instance_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_lock_test/BUILD.bazel
  oracle/controllers/instancecontroller/instance_lock_test/instance_lock_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/operator.yaml
Labels: lgtm, size/L, cla: yes, approved
