Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2021-10, with the labels that each got.

#143 [PE] Retry test cluster creation in case of GKE flakiness
  oracle/Makefile
Labels: size/XS, lgtm, cla: yes, approved

#144 Update GCSUtil with retry logic
  BUILD.bazel
  oracle/pkg/database/dbdaemon/BUILD.bazel
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/utils.go
  oracle/pkg/database/dbdaemon/utils_test.go
Labels: size/M, lgtm, cla: yes, approved

#146 Improve error handling for GCS uploads.
  oracle/pkg/database/dbdaemon/utils.go
Labels: size/XS, lgtm, cla: yes, approved

#145 Lock Instance during the restore flow. Improve error handling.
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/utils.go
Labels: size/M, lgtm, cla: yes, approved

#153 Move LoadBalancer options to common package
  common/api/v1alpha1/instance.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  oracle/api/v1alpha1/instance_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/resources.go
  oracle/operator.yaml
Labels: lgtm, size/L, cla: yes, approved

#163 Make script independent of PWD and fix logging
  oracle/controllers/instancecontroller/utils.go
  oracle/scripts/integration_test_cluster/delete_integration_test_cluster.sh
Labels: size/XS, lgtm, cla: yes, approved

#164 Dataplane enhancements
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/backup/backup.go
  oracle/pkg/agents/backup/restore.go
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/provision/bootstrap_database_task.go
Labels: lgtm, cla: yes, size/XXL, approved
