Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-03, with the labels that each got.

#190 Make containerized image generation as default
  oracle/Makefile
Labels: size/XS, lgtm, approved

#191 Remove CreateUsers API from ConfigAgent
  oracle/controllers/BUILD.bazel
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/databasecontroller/database_resources.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/main.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/BUILD.bazel
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/config_agent/server/configserver_test.go
Labels: lgtm, needs-ok-to-test, size/XXL, approved

#192 Remove CreateCDBUser, BackupStandby, CreateCDB, and CreateListener APIs from Config Agent
  oracle/controllers/BUILD.bazel
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_standby.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/controllers/user_repository.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: lgtm, size/XXL, approved

#193 Remove CreateDatabase, UsersChanged, BootstrapDatabase, and UpdateUsers APIs from Config Agent.
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_resources.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/controllers/user_repository.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/BUILD.bazel
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/config_agent/server/configserver_test.go
Labels: lgtm, size/XXL, approved

#194 Remove VerifyPhysicalBackup, PhysicalRestore, CheckStatus, and PhysicalBackup APIs from Config Agent.
  oracle/controllers/BUILD.bazel
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupcontroller/backup_controller_unit_test.go
  oracle/controllers/backupcontroller/oracle_backup.go
  oracle/controllers/backupcontroller/oracle_backup_test.go
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/resources.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/BUILD.bazel
  oracle/pkg/agents/config_agent/server/configserver.go
Labels: lgtm, size/XXL, approved

#195 Remove DataPumpImport, GetPropertyTypeValue, and DataPumpExport APIs from Config Agent.
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/exportcontroller/BUILD.bazel
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/exportcontroller/export_controller_test.go
  oracle/controllers/importcontroller/BUILD.bazel
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/importcontroller/import_controller_test.go
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/instancecontroller/instance_controller_parameters_test.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/config_agent/protos/BUILD.bazel
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/scripts/manual_test/BUILD.bazel
  oracle/scripts/manual_test/test_config_agent.go
Labels: lgtm, size/XXL, approved

#196 Remove references to Config Agent container and GRPC service.
  oracle/BUILD.bazel
  oracle/Makefile
  oracle/build/BUILD.bazel
  oracle/cmd/config_agent/BUILD.bazel
  oracle/cmd/config_agent/config_agent.go
  oracle/controllers/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupcontroller/backup_controller_unit_test.go
  oracle/controllers/backupcontroller/oracle_backup_test.go
  oracle/controllers/common.go
  oracle/controllers/configcontroller/config_controller.go
  oracle/controllers/configcontroller/config_controller_test.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/databasecontroller/database_resources.go
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/exportcontroller/export_controller_test.go
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/importcontroller/import_controller_test.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/instancecontroller/instance_controller_parameters_test.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/namespacetest/namespace_test.go
  oracle/controllers/resources.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/envtest.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/main.go
  oracle/pkg/agents/config_agent/BUILD.bazel
  oracle/pkg/agents/config_agent/protos/BUILD.bazel
  oracle/pkg/agents/config_agent/protos/service.pb.go
  oracle/pkg/agents/config_agent/protos/service.proto
  oracle/pkg/agents/config_agent/protos/service_grpc.pb.go
  oracle/pkg/agents/config_agent/server/BUILD.bazel
  oracle/pkg/agents/config_agent/server/configserver.go
  oracle/pkg/agents/config_agent/server/configserver_test.go
  oracle/pkg/agents/config_agent/server/user_repository.go
  oracle/scripts/manual_test/BUILD.bazel
  oracle/scripts/manual_test/test.go
  oracle/scripts/manual_test/test_config_agent.go
Labels: lgtm, size/XXL, approved
