Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-10, with the labels that each got.

#259 Add User guide for database patching
  docs/content/patching/database-minor-version-upgrade.md
  oracle/config/samples/v1alpha1_instance_patching.yaml
Labels: lgtm, size/L, approved

#261 Create a sample and docs for RMAN backup schedules
  docs/content/backup-restore/rman-backups.md
  oracle/config/samples/v1alpha1_backupschedule_rman1.yaml
Labels: size/M, lgtm, approved

#263 Allow setting DEFERRED database parameters.
  oracle/controllers/config_agent_helpers.go
Labels: size/XS, lgtm, ok-to-test

#265 Change wait logic for user-test
  oracle/controllers/inttest/usertest/user_test.go
Labels: size/M, lgtm, approved

#266 Suppress user related sqls
  oracle/controllers/config_agent_helpers.go
Labels: size/XS, lgtm, approved
