Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-07, with the labels that each got.

#206 Clean up doc references to configagent
  docs/content/kind.md
  docs/content/minikube.md
  docs/content/provision/config.md
  oracle/config/samples/v1alpha1_config_gcp2.yaml
  oracle/config/samples/v1alpha1_config_kind.yaml
  oracle/config/samples/v1alpha1_config_minikube.yaml
Labels: size/XS, lgtm, approved

#207 Use Internal Load Balancer in Namespace integration test
  oracle/controllers/inttest/namespacetest/namespace_test.go
Labels: size/XS, lgtm, approved

#208 Increase operator memory limits
  oracle/config/manager/manager.yaml
  oracle/operator.yaml
Labels: size/XS, lgtm, approved

#209 Increase database creation timeout
  oracle/controllers/databasecontroller/database_resources.go
Labels: size/XS, lgtm, approved

#211 Add k8s APIs for PITR
  oracle/api/v1alpha1/instance_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/operator.yaml
Labels: size/XL, lgtm, approved

#210 Delete .bazelrc file
  oracle/controllers/inttest/.bazelrc
Labels: size/XS, lgtm, approved

#212 Add DB Daemon agents for PITR
  oracle/BUILD.bazel
  oracle/pkg/agents/pitr/BUILD.bazel
  oracle/pkg/agents/pitr/pitr.go
  oracle/pkg/agents/pitr/pitr_test.go
  oracle/pkg/agents/pitr/proto/BUILD.bazel
  oracle/pkg/agents/pitr/proto/service.pb.go
  oracle/pkg/agents/pitr/proto/service.proto
  oracle/pkg/agents/pitr/proto/service_grpc.pb.go
  oracle/pkg/agents/pitr/server/BUILD.bazel
  oracle/pkg/agents/pitr/server/server.go
  oracle/pkg/util/BUILD.bazel
  oracle/pkg/util/secret/BUILD.bazel
  oracle/pkg/util/secret/secret.go
  oracle/pkg/util/task/BUILD.bazel
  oracle/pkg/util/task/task.go
  oracle/pkg/util/utils.go
  oracle/pkg/util/utils_test.go
Labels: lgtm, size/XXL, approved

#215 Update backup and backupschedule CRDs to support PITR
  oracle/api/v1alpha1/backup_types.go
  oracle/api/v1alpha1/backupschedule_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/operator.yaml
Labels: size/M, lgtm, approved

#216 Define PITR k8s CRD
  oracle/api/v1alpha1/BUILD.bazel
  oracle/api/v1alpha1/pitr_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_pitrs.yaml
Labels: lgtm, size/L, approved

#214 Add Documentation for Data Migration
  docs/content/data-migration/automated-dataguard.md
  docs/content/data-migration/automated-datapump.md
  docs/content/data-migration/manual-datapump.md
  docs/content/data-migration/manual-rman.md
  docs/content/data-migration/overview.md
  docs/content/database-env.md
Labels: lgtm, size/XXL, approved

#213 Add Documentation for PITR
  docs/content/recovery/point-in-time-recovery.md
Labels: lgtm, size/L, approved
