Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-06, with the labels that each got.

#203 Improve RunFunctionalTestSuite
  oracle/controllers/testhelpers/envtest.go
Labels: size/XS, lgtm, approved

#204 [PE] Support webhooks in test helpers, minor timeout improvements
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/configcontroller/config_controller_test.go
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/exportcontroller/export_controller_test.go
  oracle/controllers/importcontroller/import_controller_test.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/instance_lock_test/instance_lock_test.go
  oracle/controllers/inttest/.bazelrc
  oracle/controllers/testhelpers/envtest.go
  oracle/controllers/validationstest/crd_validation_test.go
Labels: lgtm, size/L, approved

#205 Imporve testhelper with webhook admission handler register
  oracle/controllers/testhelpers/envtest.go
Labels: size/S, lgtm, approved
