Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-08, with the labels that each got.

#217 Add instance lock & instance pause mode
  common/api/v1alpha1/BUILD.bazel
  common/api/v1alpha1/instance.go
  common/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/configcontroller/config_controller.go
  oracle/controllers/cronanythingcontroller/cronanything_controller.go
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/databasecontroller/database_resources.go
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/main.go
  oracle/operator.yaml
  oracle/pkg/k8s/condition.go
Labels: size/XL, lgtm, approved

#218 Add PITR Agent
  oracle/BUILD.bazel
  oracle/build/pitr_agent/Dockerfile
  oracle/cmd/pitr_agent/BUILD.bazel
  oracle/cmd/pitr_agent/pitr_agent.go
Labels: lgtm, size/L, approved

#219 Add k8s CRs for PITR Roles
  oracle/config/crd/patches/cainjection_in_pitrs.yaml
  oracle/config/crd/patches/webhook_in_pitrs.yaml
  oracle/config/rbac/pitr_editor_role.yaml
  oracle/config/rbac/pitr_viewer_role.yaml
  oracle/config/samples/v1alpha1_pitr.yaml
Labels: size/M, lgtm, approved

#220 Update test helpers for PITR
  oracle/controllers/inttest/datapumptest/datapump_test.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/envtest.go
  oracle/controllers/testhelpers/grpcmocks.go
Labels: lgtm, size/L, approved

#221 Add PITR controller
  oracle/BUILD.bazel
  oracle/Makefile
  oracle/build/BUILD.bazel
  oracle/config/crd/kustomization.yaml
  oracle/config/rbac/role.yaml
  oracle/controllers/BUILD.bazel
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupcontroller/backup_controller_unit_test.go
  oracle/controllers/backupcontroller/operations.go
  oracle/controllers/backupcontroller/oracle_backup.go
  oracle/controllers/backupcontroller/oracle_backup_test.go
  oracle/controllers/backupschedulecontroller/BUILD.bazel
  oracle/controllers/backupschedulecontroller/operations.go
  oracle/controllers/common.go
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_pitr.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/BUILD.bazel
  oracle/controllers/inttest/pitrtest/BUILD.bazel
  oracle/controllers/inttest/pitrtest/pitr_test.go
  oracle/controllers/pitrcontroller/BUILD.bazel
  oracle/controllers/pitrcontroller/operations.go
  oracle/controllers/pitrcontroller/pitr_controller.go
  oracle/controllers/pitrcontroller/pitr_controller_test.go
  oracle/controllers/resources.go
  oracle/main.go
  oracle/operator.yaml
  oracle/pkg/agents/backup/BUILD.bazel
  oracle/pkg/agents/backup/backup.go
  oracle/pkg/agents/backup/restore.go
  oracle/pkg/agents/consts/consts.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/database/dbdaemon/BUILD.bazel
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
  oracle/pkg/database/provision/bootstrap-database-listener.template
  oracle/pkg/database/provision/bootstrap-database-tnsnames.template
  oracle/pkg/database/provision/common.go
  oracle/pkg/k8s/BUILD.bazel
  oracle/pkg/k8s/finalizer/BUILD.bazel
  oracle/pkg/k8s/finalizer/finalizer.go
  oracle/scripts/integration_test_cluster/create_service_account.sh
  oracle/scripts/manual_test/BUILD.bazel
  oracle/scripts/manual_test/test.go
  oracle/scripts/manual_test/test_pitr_agent.go
Labels: lgtm, size/XXL, approved

#222 Adjust log level on successful provisioning
  oracle/cmd/init_oracle/init_oracle.go
Labels: size/XS, lgtm, approved

#223 Define constants and error msgs for Standby Migration
  oracle/controllers/standbyhelpers/BUILD.bazel
  oracle/controllers/standbyhelpers/standby_helpers.go
  oracle/pkg/agents/consts/consts.go
Labels: size/M, lgtm, approved

#224 Update the dbdaemon to support Standby Migration
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/utils.go
Labels: lgtm, size/XXL, approved

#225 Add standby migration agents
  oracle/BUILD.bazel
  oracle/controllers/BUILD.bazel
  oracle/controllers/config_agent_helpers.go
  oracle/pkg/agents/common/connect.go
  oracle/pkg/agents/security/security.go
  oracle/pkg/agents/standby/BUILD.bazel
  oracle/pkg/agents/standby/bootstrap_standby_task.go
  oracle/pkg/agents/standby/bootstrap_standby_task_test.go
  oracle/pkg/agents/standby/create_standby_task.go
  oracle/pkg/agents/standby/dbmocks.go
  oracle/pkg/agents/standby/promote_standby_task.go
  oracle/pkg/agents/standby/promote_standby_task_test.go
  oracle/pkg/agents/standby/set_up_data_guard_task.go
  oracle/pkg/agents/standby/standby.go
  oracle/pkg/agents/standby/standby_init_file_generator.go
  oracle/pkg/agents/standby/standby_test.go
  oracle/pkg/agents/standby/verify_standby_settings_task.go
  oracle/pkg/agents/standby/verify_standby_settings_task_test.go
  oracle/pkg/database/provision/bootstrap_database_task.go
Labels: lgtm, size/XXL, approved

#226 Add Standby Data Migration controller
  oracle/PROJECT
  oracle/config/samples/v1alpha1_instance_standby.yaml
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_standby.go
  oracle/controllers/inttest/BUILD.bazel
  oracle/controllers/inttest/standbydatamigrationtest/BUILD.bazel
  oracle/controllers/inttest/standbydatamigrationtest/standby_data_migration_test.go
Labels: size/XL, lgtm, approved

#230 Upgrade version number for release v0.2.0-alpha
  oracle/version.go
Labels: size/XS, lgtm, approved

#227 Increase default timeout for dbdaemon calls
  oracle/pkg/agents/common/dbdaemonlib.go
Labels: size/XS, lgtm, approved

#228 Validate CDBName in the operator CRD
  oracle/api/v1alpha1/instance_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/operator.yaml
Labels: size/S, lgtm, approved

#231 Add Dev Guide
  docs/contributors/dev-db-instance.yaml
  docs/contributors/dev-guide.md
Labels: lgtm, size/L, approved

#232 Buffer GCS downloads
  oracle/pkg/database/dbdaemon/utils.go
Labels: size/XS, lgtm, approved

#234 Remove patchstorage in image build post step
  oracle/build/dbimage/install-oracle.sh
Labels: size/XS, lgtm, approved

#235 Handle dataplane loss of LRO during backup
  oracle/controllers/backupcontroller/backup_controller.go
Labels: size/XS, lgtm, approved

#236 Cleanup unused code and dependencies
  deps.bzl
  go.mod
  go.sum
  oracle/pkg/agents/security/BUILD.bazel
  oracle/pkg/agents/security/security.go
Labels: lgtm, size/L, approved

#233 Anchor regex for CDBName
  oracle/api/v1alpha1/instance_types.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/configcontroller/config_controller_test.go
  oracle/operator.yaml
Labels: size/XS, lgtm, approved

#238 Switch to standard-rwo as the default StorageClass for GKE
  common/api/v1alpha1/config.go
  common/pkg/utils/utils.go
  docs/content/aws.md
  docs/content/backup-restore/restore-from-backups.md
  docs/content/preparation.md
  docs/content/provision/instance.md
  docs/content/quickstart-12c-ee.md
  docs/content/quickstart-18c-xe.md
  docs/content/quickstart-19c-ee.md
  docs/contributors/dev-db-instance.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/samples/v1alpha1_instance.yaml
  oracle/config/samples/v1alpha1_instance_18c_XE.yaml
  oracle/config/samples/v1alpha1_instance_19c_EE.yaml
  oracle/config/samples/v1alpha1_instance_custom_seeded.yaml
  oracle/config/samples/v1alpha1_instance_gcp_lb.yaml
  oracle/config/samples/v1alpha1_instance_with_backup_disk.yaml
  oracle/dashboards/install-dashboards.jsonnet
  oracle/operator.yaml
  oracle/scripts/deploy/csi/gce_pd_storage_class.yaml
  oracle/scripts/deploy/csi/gce_pd_volume_snapshot_class.yaml
  oracle/scripts/integration_test_cluster/create_integration_test_cluster.sh
Labels: lgtm, size/L, approved

#239 Include VolumeSnapshotClass install step in dev guide
  docs/contributors/dev-guide.md
Labels: size/S, lgtm, approved

#241 Cleanup restore test code
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_restore_test.go
Labels: size/L

#240 Make db_recovery_file_dest_size configurable
  oracle/controllers/instancecontroller/instance_controller_parameters.go
Labels: size/M, lgtm, approved

#242 Always pull Operator image
  oracle/config/manager/manager.yaml
  oracle/operator.yaml
Labels: size/XS, lgtm, approved

#237 Fix PDB deletion
  oracle/controllers/common.go
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/databasecontroller/database_controller_test.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: lgtm, size/L, approved

#243 Use standard functions to manipulate finalizers
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/pkg/k8s/BUILD.bazel
  oracle/pkg/k8s/finalizer/BUILD.bazel
  oracle/pkg/k8s/finalizer/finalizer.go
Labels: size/M, lgtm, approved

#244 Update rules to latest versions
  WORKSPACE
  common/api/v1alpha1/zz_generated.deepcopy.go
  common/controllers/operations.go
  deps.bzl
  go.mod
  go.sum
  hack/0001-Patch-to-add-bazel-support.patch
  hack/BUILD.bazel
  oracle/BUILD.bazel
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/build/BUILD.bazel
  oracle/config/crd/bases/oracle.db.anthosapis.com_databases.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/.bazelrc.tmpl
  oracle/controllers/testhelpers/envtest.go
  oracle/main.go
  oracle/operator.yaml
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.pb.go
  oracle/pkg/agents/oracle/oracle.pb.go
  oracle/pkg/agents/pitr/proto/service.pb.go
  oracle/scripts/install_prow_deps.sh
  tools.go
Labels: lgtm, size/XXL, approved
