Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-01, with the labels that each got.

#181 Changes to turn off (along with turning on) dNFS state.
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.proto
  oracle/pkg/agents/oracle/dbdaemon_proxy_grpc.pb.go
  oracle/pkg/agents/oracle/oracle.pb.go
  oracle/pkg/agents/oracle/oracle.proto
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
Labels: lgtm, size/L, approved

#182 Whitelisting certain parameters and disabling verification checks
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
Labels: size/M, lgtm, approved

#184 Update images to use numeric IDs
  oracle/BUILD.bazel
Labels: size/XS, lgtm, approved
