Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-09, with the labels that each got.

#246 Prevent the password of SYS and SYSTEM password leak
  oracle/build/dbimage/install-oracle-18c-xe.sh
  oracle/build/dbimage/install-oracle.sh
Labels: enhancement, size/XS, lgtm, ok-to-test, approved

#248 Fixes hang on timeout, tweak cron tests
  common/controllers/cronanything_controller.go
  oracle/controllers/backupschedulecontroller/functest/BUILD.bazel
  oracle/controllers/backupschedulecontroller/functest/backupschedule_controller_functional_test.go
  oracle/controllers/instancecontroller/instance_lock_test/instance_lock_test.go
Labels: size/M, lgtm, approved

#250 Assorted cleanup
  WORKSPACE
  oracle/cmd/logging/logging_main.go
  oracle/controllers/testhelpers/envtest.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/provision/bootstrap_database_task.go
Labels: size/M, lgtm, approved

#247 Add user guide for DB credentials management using GSM
  docs/content/database/database-credentials-gsm.md
Labels: documentation, lgtm, size/L, approved

#251 Fixup containerized build
  oracle/Makefile
Labels: size/XS, lgtm, approved

#252 Allow PVC retention after instance deletion
  common/api/v1alpha1/instance.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/resources.go
  oracle/operator.yaml
Labels: size/M, lgtm, approved

#253 Update Instance CRD for DB and Operator patching
  oracle/api/v1alpha1/instance_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/operator.yaml
Labels: size/M, lgtm, approved

#255 Add DbDaemon APIs for DB patching
  oracle/cmd/dbdaemon_client/dbdaemon_client.go
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/testhelpers/grpcmocks.go
  oracle/pkg/agents/oracle/dbdaemon.pb.go
  oracle/pkg/agents/oracle/dbdaemon.proto
  oracle/pkg/agents/oracle/dbdaemon_grpc.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.pb.go
  oracle/pkg/agents/oracle/dbdaemon_proxy.proto
  oracle/pkg/agents/oracle/dbdaemon_proxy_grpc.pb.go
  oracle/pkg/database/dbdaemon/BUILD.bazel
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/database/dbdaemon/dbdaemon_server_test.go
  oracle/pkg/database/dbdaemon/utils.go
  oracle/pkg/database/dbdaemon/utils_test.go
  oracle/pkg/database/dbdaemonproxy/dbdaemon_proxy.go
Labels: lgtm, size/XXL, approved

#256 Upgrade dependencies
  deps.bzl
  go.mod
  go.sum
  oracle/cmd/init_oracle/BUILD.bazel
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_configs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_cronanythings.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_databases.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_exports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_imports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_pitrs.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_releases.yaml
  oracle/config/rbac/role.yaml
  oracle/controllers/BUILD.bazel
  oracle/operator.yaml
  oracle/pkg/util/secret/BUILD.bazel
Labels: lgtm, size/XXL, approved

#257 Add Patching controller
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_patching.go
  oracle/controllers/instancecontroller/instance_controller_restore.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/instancecontroller/utils_test.go
  oracle/controllers/inttest/.bazelrc.tmpl
  oracle/controllers/inttest/BUILD.bazel
  oracle/controllers/inttest/agentpatchingtest/BUILD.bazel
  oracle/controllers/inttest/agentpatchingtest/agent_patching_test.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/inttest/patchingtest/BUILD.bazel
  oracle/controllers/inttest/patchingtest/patching_test.go
  oracle/controllers/inttest/usertest/user_test.go
  oracle/pkg/agents/backup/restore.go
  oracle/scripts/redeploy.sh
Labels: lgtm, size/XXL, approved

#258 Clean up ownerref tests
  oracle/pkg/k8s/ownerref/BUILD.bazel
  oracle/pkg/k8s/ownerref/ownerref_test.go
Labels: size/S, lgtm, approved
