Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-12, with the labels that each got.

#290 Add automatic tablespace creation
  oracle/controllers/inttest/datapumptest/datapump_test.go
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
Labels: lgtm, size/L, approved

#291 Increase MaxConcurrentReconciles for Instances to 4
  oracle/config/manager/manager.yaml
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/operator.yaml
Labels: size/S, lgtm, approved

#295 Add prep_seedpdb to image build
  oracle/build/dbimage/install-oracle.sh
Labels: size/XS, lgtm, approved

#296 Fix GSM reconciling diff
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/user_repository.go
Labels: size/S, lgtm, approved

#294 Update image build for oct DBRU
  oracle/build/dbimage/install-oracle.sh
  oracle/build/dbimage/ora19-config.sh
Labels: size/XS, lgtm, approved

#299 Add Disk Resize Feature to El Carro.
  common/pkg/utils/BUILD.bazel
  common/pkg/utils/utils.go
  oracle/config/rbac/role.yaml
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/instancetest/BUILD.bazel
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
  oracle/operator.yaml
  oracle/pkg/agents/consts/consts.go
  oracle/pkg/k8s/condition.go
Labels: size/XL, lgtm, approved

#300 Sanitize additional command parameters
  oracle/pkg/database/dbdaemon/utils.go
Labels: size/XS, lgtm, approved

#301 Relax some timeouts on immediate reconciles
  oracle/controllers/inttest/agentpatchingtest/agent_patching_test.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/controllers/inttest/patchingtest/patching_test.go
Labels: size/S, lgtm, approved

#303 Fixup metadata dump with table_exists_action
  oracle/controllers/common.go
  oracle/controllers/databasecontroller/BUILD.bazel
  oracle/controllers/databasecontroller/database_controller.go
  oracle/pkg/database/dbdaemon/BUILD.bazel
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/util/utils.go
Labels: size/M, lgtm, approved

#304 Adjust initial seeded database bootstrap
  oracle/pkg/database/provision/bootstrap_database_task.go
Labels: size/XS, lgtm, approved

#302 Drop NET_RAW capability from Dataplane containers
  oracle/controllers/resources.go
Labels: size/XS, lgtm, approved

#305 Drop NET_RAW capability from Control plane containers
  oracle/config/default/manager_auth_proxy_patch.yaml
  oracle/config/manager/manager.yaml
  oracle/operator.yaml
Labels: size/S, lgtm, approved

#306 add cpu/mem resize feature.
  oracle/controllers/common.go
  oracle/controllers/databasecontroller/database_controller.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/instancetest/instance_test.go
Labels: size/M, lgtm, approved

#307 fix: Remove finalizer from backup if Instance does not exist
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
Labels: size/S, lgtm, approved

#311 Use valid bazel testlogs directory
  oracle/Makefile
Labels: size/XS, lgtm, approved

#312 Fix log message
  oracle/controllers/instancecontroller/utils.go
Labels: size/XS, lgtm, approved

#308 Upgrade dependencies
  deps.bzl
  go.mod
  go.sum
  oracle/cmd/init_oracle/BUILD.bazel
  oracle/config/crd/bases/oracle.db.anthosapis.com_backups.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_backupschedules.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_databases.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_exports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_imports.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_instances.yaml
  oracle/config/crd/bases/oracle.db.anthosapis.com_pitrs.yaml
  oracle/config/default/manager_auth_proxy_patch.yaml
  oracle/controllers/BUILD.bazel
  oracle/controllers/config_agent_helpers.go
  oracle/operator.yaml
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
  oracle/pkg/util/secret/BUILD.bazel
  oracle/pkg/util/secret/secret.go
Labels: lgtm, size/XXL, approved
