Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2022-11, with the labels that each got.

#271 Slow down datapump int test
  oracle/controllers/inttest/datapumptest/datapump_test.go
Labels: size/XS, lgtm, approved

#272 Fix flaky instance deletion test
  oracle/controllers/inttest/instancetest/instance_test.go
Labels: size/XS, lgtm, approved

#274 Reconcile instances on changes to the config
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/inttest/instancetest/instance_test.go
Labels: size/M, lgtm, approved

#275 Save PDB state as READ WRITE
  oracle/controllers/config_agent_helpers.go
Labels: size/XS, lgtm, ok-to-test, approved

#276 Add custom monitoring agent
  BUILD.bazel
  WORKSPACE
  common/pkg/monitoring/BUILD.bazel
  common/pkg/monitoring/exporter.go
  common/pkg/monitoring/exporter_test.go
  common/pkg/monitoring/monitoring.go
  common/pkg/monitoring/monitoring_test.go
  deps.bzl
  go.mod
  go.sum
  oracle/BUILD.bazel
  oracle/build/BUILD.bazel
  oracle/cmd/dbdaemon_proxy/BUILD.bazel
  oracle/cmd/dbdaemon_proxy/dbdaemon_proxy.go
  oracle/cmd/monitoring/BUILD.bazel
  oracle/cmd/monitoring/monitoring_agent.go
  oracle/cmd/monitoring/oracle.go
  oracle/cmd/monitoring/oracle_metrics.yaml
  oracle/cmd/monitoring/oracle_unified_metrics.yaml
  oracle/controllers/common.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_patching.go
  oracle/controllers/instancecontroller/instance_controller_test.go
  oracle/controllers/instancecontroller/utils.go
  oracle/controllers/inttest/agentpatchingtest/agent_patching_test.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/resources.go
  oracle/controllers/testhelpers/envtest.go
  oracle/pkg/agents/monitoring/default-metrics.yaml
  oracle/pkg/k8s/condition.go
  third_party/monitoring/BUILD.bazel
  third_party/monitoring/LICENSE
  third_party/monitoring/README.md
  third_party/monitoring/monitoring.go
  third_party/runtime/BUILD.bazel
  third_party/runtime/LICENSE.aio
  third_party/runtime/LICENSE.nsl
  third_party/runtime/libaio.so.1
  third_party/runtime/libnsl.so.1
Labels: lgtm, size/XXL, approved

#277 Limit CIDR ranges for GKE Clusters
  oracle/scripts/integration_test_cluster/create_integration_test_cluster.sh
Labels: size/XS, lgtm, approved

#280 Fix backupschedule spec propagation
  common/controllers/backupschedule_controller.go
  common/controllers/backupschedule_controller_test.go
  common/controllers/cronanything_controller.go
  common/controllers/cronanything_controller_test.go
  oracle/controllers/cronanythingcontroller/operations.go
Labels: size/S, lgtm, approved

#281 Tweaks for test flakes
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/pkg/database/provision/common.go
Labels: size/XS, lgtm, approved

#283 Remove infinite loop from parameter update state machine
  oracle/controllers/common.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_parameters.go
  oracle/controllers/inttest/parameterupdatetest/parameter_update_test.go
  oracle/pkg/k8s/condition.go
Labels: lgtm, size/L, approved

#284 Enable setting impdp specific options on import
  oracle/api/v1alpha1/import_types.go
  oracle/api/v1alpha1/zz_generated.deepcopy.go
  oracle/config/crd/bases/oracle.db.anthosapis.com_imports.yaml
  oracle/controllers/config_agent_helpers.go
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/inttest/datapumptest/datapump_test.go
  oracle/controllers/testhelpers/envtest.go
  oracle/operator.yaml
Labels: size/M, lgtm, approved

#285 Adjust timeouts in dialers
  oracle/pkg/agents/common/dbdaemonlib.go
Labels: size/S, lgtm, approved

#286 Fixup context handling in controllers
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/exportcontroller/export_controller.go
  oracle/controllers/importcontroller/import_controller.go
  oracle/controllers/instancecontroller/instance_controller.go
  oracle/controllers/instancecontroller/instance_controller_patching.go
  oracle/controllers/inttest/instancetest/instance_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: size/M, lgtm, approved

#287 Add a retry for GCS upload
  oracle/controllers/testhelpers/envtest.go
Labels: size/XS, lgtm, approved

#288 Use a single database connection for monitoring
  common/pkg/monitoring/monitoring.go
  oracle/cmd/monitoring/oracle.go
Labels: size/S, lgtm, approved

#289 Fix: Relink config files only once
  oracle/cmd/init_oracle/init_oracle.go
Labels: size/S, lgtm, approved
