Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2023-02, with the labels that each got.

#314 Force Requeue after an Instance reaches CreateComplete state
  oracle/controllers/instancecontroller/instance_controller.go
Labels: size/XS, lgtm, approved

#315 Only set k8s.Ready to CreateComplete once
  oracle/controllers/instancecontroller/instance_controller.go
Labels: size/XS, lgtm, approved

#316 Add Changes to Support SGA/PGA Config From Memory Request
  oracle/controllers/resources.go
  oracle/controllers/resources_test.go
  oracle/pkg/database/dbdaemon/BUILD.bazel
  oracle/pkg/database/dbdaemon/dbdaemon_server.go
Labels: lgtm, size/L, approved

#319 Support update sga_target.
  oracle/controllers/config_agent_helpers.go
Labels: size/XS, lgtm, approved

#320 Return error if one occurs during CDB creation
  oracle/controllers/instancecontroller/instance_controller.go
Labels: size/XS, lgtm, approved

#321 amend dbdclient log lines.
  oracle/controllers/config_agent_helpers.go
Labels: size/S, lgtm, approved
