Repository GoogleCloudPlatform/elcarro-oracle-operator, pull requests merged in 2023-11, with the labels that each got.

#347 feat: Remove cluster cleanup in presubmits
  oracle/Makefile
Labels: size/S, lgtm, approved

#348 fix: cluster cleanup logic in presubmits
  oracle/Makefile
Labels: size/S, lgtm, approved

#349 fix: remove redundant GKE workload configuration
  oracle/controllers/inttest/standbydatamigrationtest/standby_data_migration_test.go
  oracle/controllers/inttest/usertest/user_test.go
  oracle/controllers/testhelpers/envtest.go
Labels: size/S, lgtm, approved

#350 chore: update VolumeSnapshot API to restore compatibility with k8s 1.27
  common/pkg/utils/BUILD.bazel
  common/pkg/utils/utils.go
  deps.bzl
  go.mod
  go.sum
  oracle/BUILD.bazel
  oracle/config/crd/testing/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  oracle/config/crd/testing/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  oracle/config/crd/testing/snapshot.storage.k8s.io_volumesnapshots.yaml
  oracle/controllers/BUILD.bazel
  oracle/controllers/backupcontroller/BUILD.bazel
  oracle/controllers/backupcontroller/backup_controller.go
  oracle/controllers/backupcontroller/backup_controller_test.go
  oracle/controllers/backupcontroller/oracle_backup.go
  oracle/controllers/instancecontroller/BUILD.bazel
  oracle/controllers/instancecontroller/instance_controller_patching.go
  oracle/controllers/inttest/snapbackuptest/BUILD.bazel
  oracle/controllers/inttest/snapbackuptest/snapshot_backup_test.go
  oracle/controllers/resources.go
  oracle/controllers/testhelpers/BUILD.bazel
  oracle/controllers/testhelpers/envtest.go
  oracle/main.go
Labels: size/XL, lgtm, approved

#353 Add tabbyl21 to OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#354 oracle/controllers/instancecontroller: fix dropped error
  oracle/controllers/instancecontroller/instance_controller_patching.go
Labels: size/XS, lgtm, needs-ok-to-test, approved
